#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cargo
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : cbindgen
Version  : 0.26.0
Release  : 1
URL      : https://github.com/mozilla/cbindgen/archive/refs/tags/0.26.0.tar.gz
Source0  : https://github.com/mozilla/cbindgen/archive/refs/tags/0.26.0.tar.gz
Source1  : http://localhost/cgit/vendor/cbindgen/snapshot/cbindgen-2024-06-17-16-13-06.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0 MIT MPL-2.0-no-copyleft-exception Unicode-DFS-2016 Unlicense
Requires: cbindgen-bin = %{version}-%{release}
Requires: cbindgen-license = %{version}-%{release}
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# `cbindgen` &emsp; [![Build Status]][actions] [![Latest Version]][crates.io] [![Api Rustdoc]][rustdoc] [![Rust](https://img.shields.io/badge/rust-1.64%2B-blue.svg?maxAge=3600)](https://github.com/mozilla/cbindgen)

%package bin
Summary: bin components for the cbindgen package.
Group: Binaries
Requires: cbindgen-license = %{version}-%{release}

%description bin
bin components for the cbindgen package.


%package license
Summary: license components for the cbindgen package.
Group: Default

%description license
license components for the cbindgen package.


%prep
%setup -q -n cbindgen-0.26.0
cd %{_builddir}
tar xf %{_sourcedir}/cbindgen-2024-06-17-16-13-06.tar.xz
cd %{_builddir}/cbindgen-0.26.0
mkdir -p ./vendor
cp -r %{_builddir}/cbindgen-2024-06-17-16-13-06/* %{_builddir}/cbindgen-0.26.0/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cargo build --release

%install
mkdir -p %{buildroot}/usr/share/package-licenses/cbindgen
cp %{_builddir}/cbindgen-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/cbindgen/d22157abc0fc0b4ae96380c09528e23cf77290a9 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/atty/LICENSE %{buildroot}/usr/share/package-licenses/cbindgen/3acad00f27f89710cd66d3f5528aed5046ac28d9 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/clap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/clap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/clap_lex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/clap_lex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/8fe88f09d35c6054e0a780a793833c16fb888168 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/hashbrown/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/hashbrown/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/hermit-abi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/hermit-abi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/indexmap/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/indexmap/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/7e5936a6fa3cf3518c01cec41345adf27399fe12 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/instant/LICENSE %{buildroot}/usr/share/package-licenses/cbindgen/037192733999bccd7ed8d75123b7ec09feb4a12d || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/aca374a3362a76702c50bd4e7d590a57f8834fc7 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/f9cc84dfc567fdc0979fddc3e6257191d8ebc9d8 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/os_str_bytes/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/os_str_bytes/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/dace34da2cc966a228ddef52cbc28943931af544 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/cbindgen/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/remove_dir_all/LICENCE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/8fd4530045d4f57b4a4447e19147f4e70286e3b3 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/remove_dir_all/LICENCE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/1299388f703aa63092d01668958767dc0f0ef3a3 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/cbindgen/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/serial_test/LICENSE %{buildroot}/usr/share/package-licenses/cbindgen/f325abb79af13a6fddd6cfdb1117182bc0893541 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/serial_test_derive/LICENSE %{buildroot}/usr/share/package-licenses/cbindgen/f325abb79af13a6fddd6cfdb1117182bc0893541 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/strsim/LICENSE %{buildroot}/usr/share/package-licenses/cbindgen/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/syn-1.0.109/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/syn-1.0.109/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/termcolor/COPYING %{buildroot}/usr/share/package-licenses/cbindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/termcolor/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/termcolor/UNLICENSE %{buildroot}/usr/share/package-licenses/cbindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/textwrap/LICENSE %{buildroot}/usr/share/package-licenses/cbindgen/70e36c2f54755e87728778c41ab4b809e5b0b502 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/toml/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/toml/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/cbindgen/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/cbindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/cbindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/winapi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/cbindgen/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/cbindgen-2024-06-17-16-13-06/winapi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/cbindgen/2243f7a86daaa727d34d92e987a741036f288464 || :
cargo install --path . && mkdir -p %{buildroot}/usr/bin && pushd "${HOME}/.cargo/bin/" && mv * %{buildroot}/usr/bin/ && popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cbindgen

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cbindgen/037192733999bccd7ed8d75123b7ec09feb4a12d
/usr/share/package-licenses/cbindgen/1299388f703aa63092d01668958767dc0f0ef3a3
/usr/share/package-licenses/cbindgen/2243f7a86daaa727d34d92e987a741036f288464
/usr/share/package-licenses/cbindgen/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/cbindgen/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/cbindgen/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/cbindgen/3acad00f27f89710cd66d3f5528aed5046ac28d9
/usr/share/package-licenses/cbindgen/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/cbindgen/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/cbindgen/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/cbindgen/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/cbindgen/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/cbindgen/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/cbindgen/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/cbindgen/70693ba8757c4a17af68e39ab32e4e0d4a389416
/usr/share/package-licenses/cbindgen/70e36c2f54755e87728778c41ab4b809e5b0b502
/usr/share/package-licenses/cbindgen/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/cbindgen/7e5936a6fa3cf3518c01cec41345adf27399fe12
/usr/share/package-licenses/cbindgen/8fd4530045d4f57b4a4447e19147f4e70286e3b3
/usr/share/package-licenses/cbindgen/8fe88f09d35c6054e0a780a793833c16fb888168
/usr/share/package-licenses/cbindgen/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/cbindgen/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/cbindgen/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/cbindgen/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/cbindgen/aca374a3362a76702c50bd4e7d590a57f8834fc7
/usr/share/package-licenses/cbindgen/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/cbindgen/c9c1c33aee599ebfdfb0bc2aed9ea082d9e3173a
/usr/share/package-licenses/cbindgen/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/cbindgen/d22157abc0fc0b4ae96380c09528e23cf77290a9
/usr/share/package-licenses/cbindgen/dace34da2cc966a228ddef52cbc28943931af544
/usr/share/package-licenses/cbindgen/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/cbindgen/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/cbindgen/f325abb79af13a6fddd6cfdb1117182bc0893541
/usr/share/package-licenses/cbindgen/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/cbindgen/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/cbindgen/f9cc84dfc567fdc0979fddc3e6257191d8ebc9d8
/usr/share/package-licenses/cbindgen/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
